# Generated by Django 4.1 on 2022-08-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.CharField(max_length=100)),
                ('todo_status', models.CharField(default='NOT DONE', max_length=5)),
            ],
        ),
    ]
