# Generated by Django 4.1 on 2022-08-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_todoitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
