# Generated by Django 4.1 on 2022-08-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_task_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='topic',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
