# Generated by Django 4.1 on 2022-08-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_task_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='topic',
            new_name='discription',
        ),
    ]
